# docker-compose.yml
version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  good-food:
    build: .
    image: api
    ports:
      - '4000:4000'
    networks: 
      - app-network
    environment: 
      - DB_URI=mongodb://mongo:27017/good-food
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    networks: 
      - app-network


