# docker-compose.yml
version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  good-food-api:
    build: .
    ports:
      - '8080:8080'
    networks: 
      - app-network
    environment: 
      - DB_URI=mongodb://mongo:27017/good-food
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data/:/data/db
    networks: 
      - app-network
  # influxdb:
  #   image: influxdb:latest     
  #   ports:
  #     - "8086:8086"
  #   volumes:
  #     - ./data/influxdb:/var/lib/influxdb
  #   environment:
  #     - INFLUXDB_DB=winston
  # chronograf:
  #   image: chronograf:latest
  #   entrypoint: 'chronograf --influxdb-url=http://influxdb:8086'
  #   depends_on: ['influxdb']
  #   ports:
  #     - "8888:8888"


